// Generated by CoffeeScript 1.8.0
var Tugboat, expect;

expect = require('chai').expect;

Tugboat = require('../src/tugboat');

describe('Tugboat', function() {
  return it('should have sensible defaults', function() {
    var tug;
    return tug = new Tugboat();
  });
});
