// Generated by CoffeeScript 1.8.0
module.exports = function(tugboat, ducke, seq, group, service, container, callback) {
  if (!container.inspect.State.Running) {
    seq('Starting', function(cb) {
      return tugboat.start(group, service, container, cb);
    });
  }
  return callback();
};
