// Generated by CoffeeScript 1.8.0
module.exports = function(tugboat, ducke, group, service, container, callback) {
  if (container.inspect.State.Running) {
    return callback(null);
  }
  return tugboat.start(group, service, container, callback);
};
