// Generated by CoffeeScript 1.9.1
var getcorrectname,
  indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

getcorrectname = function(names) {
  var i, len, name;
  for (i = 0, len = names.length; i < len; i++) {
    name = names[i];
    name = name.slice(1);
    if (indexOf.call(name, '/') < 0) {
      return name;
    }
  }
  return names[0].slice(1);
};

module.exports = function(groups, statuses) {
  var chunks, g, group, groupname, i, index, len, name, names, ref, results, service, status;
  results = {};
  for (groupname in groups) {
    group = groups[groupname];
    g = {
      name: groupname,
      group: group,
      isknown: true,
      services: {}
    };
    ref = group.services;
    for (name in ref) {
      service = ref[name];
      g.services[name] = {
        name: name,
        service: service,
        isknown: true,
        containers: []
      };
    }
    results[groupname] = g;
  }
  for (i = 0, len = statuses.length; i < len; i++) {
    status = statuses[i];
    names = status.container.Names;
    name = getcorrectname(names);
    chunks = name.split('_');
    if (chunks.length !== 3) {
      continue;
    }
    groupname = chunks[0], name = chunks[1], index = chunks[2];
    if (results[groupname] == null) {
      results[groupname] = {
        name: groupname,
        group: null,
        isknown: false,
        services: {}
      };
    }
    group = results[groupname];
    if (group.services[name] == null) {
      group.services[name] = {
        name: name,
        service: null,
        isknown: false,
        containers: []
      };
    }
    group.services[name].containers.push({
      index: index,
      container: status.container,
      inspect: status.inspect
    });
  }
  return results;
};
