// Generated by CoffeeScript 1.8.0
module.exports = function(groups, containers) {
  var c, chunks, container, g, group, groupname, index, name, results, _i, _len, _ref;
  results = {};
  for (groupname in groups) {
    group = groups[groupname];
    g = {
      name: groupname,
      group: group,
      isknown: true,
      containers: {}
    };
    _ref = group.containers;
    for (name in _ref) {
      container = _ref[name];
      g.containers[name] = {
        name: name,
        container: container,
        isknown: true,
        indexes: []
      };
    }
    results[groupname] = g;
  }
  for (_i = 0, _len = containers.length; _i < _len; _i++) {
    c = containers[_i];
    name = c.container.Names[0].substr(1);
    chunks = name.split('_');
    if (chunks.length !== 3) {
      continue;
    }
    groupname = chunks[0], name = chunks[1], index = chunks[2];
    if (results[groupname] == null) {
      results[groupname] = {
        name: groupname,
        group: null,
        isknown: false,
        containers: {}
      };
    }
    group = results[groupname];
    if (group.containers[name] == null) {
      group.containers[name] = {
        name: name,
        container: null,
        isknown: false,
        indexes: []
      };
    }
    container = group.containers[name];
    container.indexes.push({
      index: index,
      container: c.container,
      inspect: c.inspect
    });
  }
  return results;
};
