// Generated by CoffeeScript 1.8.0
module.exports = function(groups, statuses) {
  var chunks, g, group, groupname, index, name, results, service, status, _i, _len, _ref;
  results = {};
  for (groupname in groups) {
    group = groups[groupname];
    g = {
      name: groupname,
      group: group,
      isknown: true,
      services: {}
    };
    _ref = group.services;
    for (name in _ref) {
      service = _ref[name];
      g.services[name] = {
        name: name,
        service: service,
        isknown: true,
        containers: []
      };
    }
    results[groupname] = g;
  }
  for (_i = 0, _len = statuses.length; _i < _len; _i++) {
    status = statuses[_i];
    name = status.container.Names[0].substr(1);
    chunks = name.split('_');
    if (chunks.length !== 3) {
      continue;
    }
    groupname = chunks[0], name = chunks[1], index = chunks[2];
    if (results[groupname] == null) {
      results[groupname] = {
        name: groupname,
        group: null,
        isknown: false,
        services: {}
      };
    }
    group = results[groupname];
    if (group.services[name] == null) {
      group.services[name] = {
        name: name,
        service: null,
        isknown: false,
        containers: []
      };
    }
    service = group.services[name];
    service.containers.push({
      index: index,
      container: status.container,
      inspect: status.inspect
    });
  }
  return results;
};
