// Generated by CoffeeScript 1.8.0
var Seq, delay,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

delay = function(f) {
  return setTimeout(f, 0);
};

Seq = (function() {
  function Seq() {
    this.push = __bind(this.push, this);
    this._error = __bind(this._error, this);
    this._next = __bind(this._next, this);
    this._frames = [];
  }

  Seq.prototype._next = function() {
    var item;
    while (this._frames.length !== 0 && this._frames[0].length === 0) {
      this._frames.shift();
    }
    if (this._frames.length === 0) {
      return;
    }
    item = this._frames[0].shift();
    this._frames.unshift([]);
    if (item.description != null) {
      return item.action((function(_this) {
        return function(err) {
          if (err != null) {
            console.log("  " + item.description + " " + 'X'.red);
            return _this._error(err);
          }
          console.log("  " + item.description + " " + '√'.green);
          return _this._next();
        };
      })(this));
    } else {
      return item.action((function(_this) {
        return function(err) {
          if (err != null) {
            return _this._error(err);
          }
          return _this._next();
        };
      })(this));
    }
  };

  Seq.prototype._error = function(err) {
    var m, _i, _len, _results;
    if (typeof err === 'Array') {
      _results = [];
      for (_i = 0, _len = err.length; _i < _len; _i++) {
        m = err[_i];
        _results.push(console.error(m));
      }
      return _results;
    } else if (err.stack != null) {
      return console.error(err.stack);
    } else {
      return console.error(err);
    }
  };

  Seq.prototype.push = function(description, action) {
    if (action == null) {
      action = description;
      description = null;
    }
    if (this._frames.length === 0) {
      this._frames.push([]);
      delay((function(_this) {
        return function() {
          return _this._next();
        };
      })(this));
    }
    return this._frames[0].push({
      description: description,
      action: action
    });
  };

  return Seq;

})();

module.exports = new Seq().push;
