// Generated by CoffeeScript 1.8.0
var containerdiff, identifyprimary, servicediff;

containerdiff = require('./containerdiff');

identifyprimary = function(service, imagerepo) {
  var c, difference, image, result, tagname, _i, _len, _ref;
  tagname = service.service.params.Image;
  if (tagname.indexOf(':') === -1) {
    tagname += ':latest';
  }
  if (imagerepo.tags[tagname] == null) {
    return {
      messages: ["Image '" + service.service.params.Image + "' not found"],
      error: service.containers,
      iserror: true,
      keep: [],
      migrate: [],
      cull: []
    };
  }
  image = imagerepo.tags[tagname];
  result = {
    messages: [],
    error: [],
    iserror: false,
    keep: [],
    migrate: [],
    cull: []
  };
  _ref = service.containers;
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    c = _ref[_i];
    if (result.keep.length !== 0) {
      result.cull.push(c);
      continue;
    }
    difference = containerdiff(c, service, image);
    if (difference == null) {
      result.keep.push(c);
    } else {
      result.messages.push(difference);
      result.migrate.push(c);
    }
  }
  return result;
};

servicediff = function(group, service, imagerepo) {
  var cull, d, e, error, iserror, k, keep, m, messages, migrate, result, _i, _j, _k, _l, _len, _len1, _len2, _len3, _len4, _m, _ref;
  result = {
    messages: [],
    error: [],
    iserror: false,
    keep: [],
    migrate: [],
    cull: [],
    create: 0
  };
  if (!service.isknown) {
    result.messages.push('Unknown service.');
    return result;
  }
  _ref = identifyprimary(service, imagerepo), messages = _ref.messages, error = _ref.error, iserror = _ref.iserror, keep = _ref.keep, migrate = _ref.migrate, cull = _ref.cull;
  for (_i = 0, _len = messages.length; _i < _len; _i++) {
    m = messages[_i];
    result.messages.push(m);
  }
  for (_j = 0, _len1 = error.length; _j < _len1; _j++) {
    e = error[_j];
    result.error.push(e);
  }
  result.iserror = iserror;
  for (_k = 0, _len2 = keep.length; _k < _len2; _k++) {
    k = keep[_k];
    if (!k.inspect.State.Running) {
      result.start.push(k);
    } else {
      result.keep.push(k);
    }
  }
  for (_l = 0, _len3 = migrate.length; _l < _len3; _l++) {
    m = migrate[_l];
    result.migrate.push(m);
  }
  for (_m = 0, _len4 = cull.length; _m < _len4; _m++) {
    d = cull[_m];
    result.cull.push(d);
  }
  if (!result.iserror) {
    while (result.create + keep.length + migrate.length < 1) {
      result.create++;
    }
  }
  return result;
};

module.exports = function(imagerepo, groups) {
  var g, s, _, _ref;
  for (_ in groups) {
    g = groups[_];
    _ref = g.services;
    for (_ in _ref) {
      s = _ref[_];
      s.diff = servicediff(g, s, imagerepo);
    }
  }
  return groups;
};
