// Generated by CoffeeScript 1.8.0
var containerdiff, identifyprimary, servicediff;

containerdiff = require('./containerdiff');

identifyprimary = function(service, imagerepo) {
  var c, difference, image, result, tagname, _i, _len, _ref;
  if (!service.isknown) {
    return {
      messages: ["Unknown service " + service.name + ", restart everything"],
      keep: [],
      discard: service.containers,
      error: [],
      iserror: true
    };
  }
  tagname = service.service.params.Image;
  if (tagname.indexOf(':') === -1) {
    tagname += ':latest';
  }
  if (imagerepo.tags[tagname] == null) {
    return {
      messages: ["Image '" + service.service.params.Image + "' not found"],
      keep: [],
      discard: [],
      error: service.containers,
      iserror: true
    };
  }
  image = imagerepo.tags[tagname];
  result = {
    messages: [],
    keep: [],
    discard: [],
    error: [],
    iserror: false
  };
  _ref = service.containers;
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    c = _ref[_i];
    if (result.keep.length !== 0) {
      result.discard.push(c);
      continue;
    }
    difference = containerdiff(c, service, image);
    if (difference == null) {
      result.keep.push(c);
    } else {
      result.messages.push(difference);
      result.discard.push(c);
    }
  }
  return result;
};

servicediff = function(group, service, imagerepo) {
  var d, discard, e, error, iserror, k, keep, m, messages, result, _i, _j, _k, _l, _len, _len1, _len2, _len3, _ref;
  result = {
    messages: [],
    stop: [],
    rm: [],
    start: [],
    keep: [],
    error: [],
    create: 0,
    iserror: false
  };
  if (!service.isknown) {
    result.messages.push('Unknown service, starting anything that is stopped.');
    result.start = service.containers.filter(function(c) {
      return !c.inspect.State.Running;
    });
    return result;
  }
  _ref = identifyprimary(service, imagerepo), messages = _ref.messages, keep = _ref.keep, discard = _ref.discard, error = _ref.error, iserror = _ref.iserror;
  for (_i = 0, _len = keep.length; _i < _len; _i++) {
    k = keep[_i];
    if (!k.inspect.State.Running) {
      result.start.push(k);
    } else {
      result.keep.push(k);
    }
  }
  for (_j = 0, _len1 = discard.length; _j < _len1; _j++) {
    d = discard[_j];
    if (d.inspect.State.Running) {
      result.stop.push(d);
    }
    result.rm.push(d);
  }
  for (_k = 0, _len2 = error.length; _k < _len2; _k++) {
    e = error[_k];
    result.error.push(e);
  }
  for (_l = 0, _len3 = messages.length; _l < _len3; _l++) {
    m = messages[_l];
    result.messages.push(m);
  }
  result.iserror = iserror;
  if (!result.iserror) {
    while (result.create + keep.length < 1) {
      result.create++;
    }
  }
  return result;
};

module.exports = function(imagerepo, groups) {
  var g, s, _, _ref;
  for (_ in groups) {
    g = groups[_];
    _ref = g.services;
    for (_ in _ref) {
      s = _ref[_];
      s.diff = servicediff(g, s, imagerepo);
    }
  }
  return groups;
};
