// Generated by CoffeeScript 1.8.0
var os, template;

os = require('os');

template = function(content) {
  var key, type, value;
  type = typeof content;
  if (type === 'object') {
    for (key in content) {
      value = content[key];
      delete content[key];
      key = template(key);
      value = template(value);
      content[key] = value;
    }
    return content;
  } else if (type === 'string') {
    return content.replace(/#\{([a-zA-Z0-9_]+?)\}/g, function(match, token) {
      if (process.env[token] != null) {
        return process.env[token];
      } else if (token === 'HOST' || token === 'HOSTNAME') {
        return os.hostname();
      } else {
        return match;
      }
    });
  } else if (type === 'array') {
    return content.map(function(i) {
      return template(i);
    });
  } else {
    return content;
  }
};

module.exports = template;
